name: Unity EditMode Test Runner

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  editmode-tests:
    name: Run EditMode Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - name: Cache Library
      uses: actions/cache@v3
      with:
        path: Library
        key: Library-${{ runner.os }}-${{ hashFiles('**/Assets/**', '**/Packages/**', '**/ProjectSettings/**') }}

    - name: Set up Unity
      uses: game-ci/unity-setup@v3
      with:
        unityVersion: 6000.0.47f1

    - name: Run EditMode Tests
      uses: game-ci/unity-test-runner@v3
      with:
        testMode: EditMode
        githubToken: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: EditMode-Test-Results
        path: artifacts
